### ISSUE TITLE
Values with 4 or more digits and a zero next to the dot do not convert properly

### ISSUE THREAD

**Issue by timvandevelde** [chuckcarpenter/REM-unit-polyfill#59]
My rems are 10px. If I set a width of 80rem it converts nicely to 800px. 101.3rem converts to 1013px. 80.52rem converts to 805px. 

But if I set a width of 120.8rem, it converts to 128.8px. 
80.50rem converts to 80.5px. 

Looks like it has something to do with the zero before the dot.

**Comment by chuckcarpenter** [comment]
@timvandevelde I'm not able to replicate based on the use case of just the 0 before the dot. e.g., 

``` css
html {
    font-size: 10px;
   -webkit-text-size-adjust: 100%;
   -ms-text-size-adjust: 100%;
    line-height: 1.6;
}
.test {
    background-color:black !important;
    color: white;
    width: 50.5rem;
    height: 5em;
}
```

Will give me:

``` css
.test {
  width: 505px;
}
```

Can you share your project or more specifics?
