### ISSUE TITLE
Does not support REM units in media queries

### ISSUE THREAD

**Issue by ghost** [chuckcarpenter/REM-unit-polyfill#62]
Like it says in the general.css, media queries like 

``` css
@media screen and (min-width: 480px) {
    p {
        font-size: 10rem;
    }
    .test {
        background-color: red;
        border: 1px solid yellow;
        font-size: 3rem;
    }
}
```

are not supported. Does this mean in my stylesheet that if I use media queries based on REM units I will have to make a separate stylesheet for IE8 and there use PX units for my media queries?

Is there a way to tell REM.js to accept REM units in media queries perhaps?
Would love to be able to use REM.js with something like below.

``` css
@media screen and (min-width: 30rem) {
    p {
        font-size: 10rem;
    }
    .test {
        background-color: red;
        border: 1px solid yellow;
        font-size: 3rem;
    }
}
```

If that is not possibly I assume it was a wanted decision to not support REM units in media queries. If so I would like to hear why those have been left out, apparently with a purpose. Curious to what that purpose is. Perhaps that can help me understand better.

If you can just let me know if or why REM units in media queries are not supported that would be great.

Thank you for your time and help.
